### ISSUE TITLE
Help with Mount Paths for Settings.yaml in GraphRAG Docker Compose Setup

### ISSUE THREAD

**Issue by arsaboo** [Cinnamon/kotaemon#414]
### Description

I'm trying to use GraphRAG with local models and I'm a bit confused about the mount paths, specifically where to place the `settings.yaml` file so that it can be loaded correctly. Here's my current `docker-compose.yml` configuration:

```yaml
services:
  kotaemon:
    image: ghcr.io/cinnamon/kotaemon:main-full
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    ports:
      - "7866:7860"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /Users/arsaboo/Documents/Containers/kotaemon/data:/app/ktem_app_data
```

Could you please clarify where I should place the `settings.yaml` file so that it is accessible to the service? 

Thanks!
